repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit # Drop-in replacement for black, isort, pydocstyle, and flake8 
    rev: v0.2.2
    hooks:
      - id: ruff
        exclude: "^tests/|^scripts/"
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true